base_url = "https://blog.geokkjer.eu"
title = "Geokkjer"

theme = "sam"

compile_sass = true

highlight_code = true
highlight_theme = "boron"

build_search_index = false

check_external_links = true

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "about", link = "/about" },
    { text = "github", link = "https://github.com/geokkjer" }
]

sam_bottom_menu = true

[extra.sam_footer]
text = "Some footer text."