base_url = "https://blog.geokkjer.eu"
title = "geokkjer.eu"

theme = "sam"
build_search_index = true

check_external_links = true
compile_sass = true

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "k8s", link = "/kubernetes" },
    { text = "linux", link = "/Linux" },
    { text = "github", link = "https://github.com/geokkjer" },
    { text = "about", link = "/about" }
    
]

sam_bottom_menu = true

[extra.sam_footer]
text = "Some footer text."